import { AppData, AccountNode } from '../types';
import { ensureProductPricesSynced } from './priceService';
import { DEFAULT_COMPANIES } from './multiTenantService';

export const STORAGE_KEY = 'accounting_system_v8';

export const defaultAccountsTree: AccountNode[] = [
  // 1 - الأصول
  { code: '1', name: 'الأصول (Assets)', type: 'asset', isParent: true, debit: 0, credit: 0, balance: 0 },
  { code: '11', name: 'الأصول المتداولة (Current Assets)', type: 'asset', parentCode: '1', isParent: true, debit: 0, credit: 0, balance: 0 },
  { code: '1101', name: 'الصندوق والخزينة الرئيسية (Cash)', type: 'asset', parentCode: '11', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '1102', name: 'فودافون كاش والمحافظ الإلكترونية', type: 'asset', parentCode: '11', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '1103', name: 'إنستاباي (InstaPay)', type: 'asset', parentCode: '11', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '1104', name: 'الحسابات البنكية (Bank Accounts)', type: 'asset', parentCode: '11', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '1105', name: 'العملاء والمدينون (Accounts Receivable)', type: 'asset', parentCode: '11', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '1106', name: 'مخزون البضاعة (Merchandise Inventory)', type: 'asset', parentCode: '11', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '12', name: 'الأصول الثابتة (Fixed Assets)', type: 'asset', parentCode: '1', isParent: true, debit: 0, credit: 0, balance: 0 },
  { code: '1201', name: 'الأثاث والمعدات المكتبية', type: 'asset', parentCode: '12', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '1202', name: 'أجهزة الكمبيوتر والتكنولوجيا', type: 'asset', parentCode: '12', isParent: false, debit: 0, credit: 0, balance: 0 },

  // 2 - الخصوم
  { code: '2', name: 'الخصوم والالتزامات (Liabilities)', type: 'liability', isParent: true, debit: 0, credit: 0, balance: 0 },
  { code: '21', name: 'الخصوم المتداولة (Current Liabilities)', type: 'liability', parentCode: '2', isParent: true, debit: 0, credit: 0, balance: 0 },
  { code: '2101', name: 'الموردون والدائنون (Accounts Payable)', type: 'liability', parentCode: '21', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '2102', name: 'أمانات ضريبة القيمة المضافة (VAT Payable)', type: 'liability', parentCode: '21', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '2103', name: 'ضريبة الخصم والتحصيل من المنبع', type: 'liability', parentCode: '21', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '2104', name: 'مصروفات مستحقة الدفع', type: 'liability', parentCode: '21', isParent: false, debit: 0, credit: 0, balance: 0 },

  // 3 - حقوق الملكية
  { code: '3', name: 'حقوق الملكية (Owner\'s Equity)', type: 'equity', isParent: true, debit: 0, credit: 0, balance: 0 },
  { code: '3101', name: 'رأس المال المستثمر (Capital)', type: 'equity', parentCode: '3', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '3102', name: 'الأرباح والخسائر المرحلة (Retained Earnings)', type: 'equity', parentCode: '3', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '3103', name: 'جاري صاحب المنشأة / الشركاء', type: 'equity', parentCode: '3', isParent: false, debit: 0, credit: 0, balance: 0 },

  // 4 - الإيرادات
  { code: '4', name: 'الإيرادات والمبيعات (Revenues)', type: 'revenue', isParent: true, debit: 0, credit: 0, balance: 0 },
  { code: '4101', name: 'إيراد مبيعات بضاعة تجارية (Sales Revenue)', type: 'revenue', parentCode: '4', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '4102', name: 'مردودات ومسموحات المبيعات (Sales Returns)', type: 'revenue', parentCode: '4', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '4103', name: 'إيرادات خدمات وشحن وصيانة', type: 'revenue', parentCode: '4', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '4104', name: 'خصم مسموح به (Sales Discounts)', type: 'revenue', parentCode: '4', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '4201', name: 'أرباح وفروقات تسوية المخزون (Inventory Adjustment Gain)', type: 'revenue', parentCode: '4', isParent: false, debit: 0, credit: 0, balance: 0 },

  // 5 - المصروفات
  { code: '5', name: 'المصروفات وتكلفة البضاعة (Expenses & COGS)', type: 'expense', isParent: true, debit: 0, credit: 0, balance: 0 },
  { code: '5101', name: 'تكلفة البضاعة المباعة (Cost of Goods Sold - COGS)', type: 'expense', parentCode: '5', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '5201', name: 'مصروفات الإيجار والمرافق', type: 'expense', parentCode: '5', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '5202', name: 'الرواتب والأجور والمكافآت', type: 'expense', parentCode: '5', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '5203', name: 'مصاريف الدعاية والتسويق', type: 'expense', parentCode: '5', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '5204', name: 'مصاريف الصيانة والتشغيل والنثريات', type: 'expense', parentCode: '5', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '5205', name: 'عمولات المندوبين والمبيعات', type: 'expense', parentCode: '5', isParent: false, debit: 0, credit: 0, balance: 0 },
  { code: '5206', name: 'عجز وفاقد تسوية المخزون (Inventory Shrinkage & Loss)', type: 'expense', parentCode: '5', isParent: false, debit: 0, credit: 0, balance: 0 },
];

export function getDefaultData(): AppData {
  return {
    settings: {
      companyName: 'النزيه للمحاسبة',
      address: 'القاهرة، مصر',
      phone1: '01029190615',
      phone2: '01100000000',
      phone3: '01200000000',
      taxNumber: '123-456-789',
      commercialReg: 'CR-98765',
      activityCode: '4651 - تجارة أجهزة وإلكترونيات',
      notes: 'شكراً لتعاملكم مع نظام النزيه للمحاسبة',
      defaultTaxRate: 14,
      withholdingTaxRate: 1,
      currencySymbol: 'ج.م',
      fiscalYear: '2026',
    },
    users: [
      {
        id: 'user1',
        name: 'Mohamed Nazih (المدير)',
        username: 'admin',
        password: 'admin123',
        role: 'admin',
        permissions: { all: true },
      },
      {
        id: 'user2',
        name: 'كاشير الفرع الرئيسي',
        username: 'cashier',
        password: '123',
        role: 'user',
        permissions: { sales: true, pos: true, quotes: true },
      },
    ],
    currentUser: 'user1',
    customers: [
      {
        id: 'c1',
        name: 'شركة النور للتجارة',
        phone: '01011111111',
        balance: 0,
        taxNumber: '321-654-987',
        commercialReg: '12345',
        address: 'مدينة نصر، القاهرة',
        priceTier: 'wholesale',
        creditLimit: 50000,
        transactions: [],
      },
      {
        id: 'c2',
        name: 'مؤسسة السلام الحديثة',
        phone: '01022222222',
        balance: 0,
        taxNumber: '444-555-666',
        address: 'الدقي، الجيزة',
        priceTier: 'retail',
        creditLimit: 20000,
        transactions: [],
      },
      {
        id: 'c3',
        name: 'شركة الأمل للمقاولات',
        phone: '01033333333',
        balance: 0,
        address: 'التجمع الخامس، القاهرة',
        priceTier: 'special',
        transactions: [],
      },
    ],
    suppliers: [
      {
        id: 's1',
        name: 'مصنع الخير للإلكترونيات',
        phone: '01111111111',
        balance: 0,
        taxNumber: '777-888-999',
        address: 'مدينة العاشر من رمضان',
        transactions: [],
      },
      {
        id: 's2',
        name: 'شركة الرازي للاستيراد',
        phone: '01122222222',
        balance: 0,
        taxNumber: '111-222-333',
        address: 'المهندسين، الجيزة',
        transactions: [],
      },
      {
        id: 's3',
        name: 'مؤسسة النيل للتوريدات',
        phone: '01133333333',
        balance: 0,
        transactions: [],
      },
    ],
    items: [
      {
        id: 'i1',
        companyId: 'COMP-000001',
        name: 'جهاز كمبيوتر Core i7 Desktop',
        barcode: '62210010001',
        category: 'أجهزة كمبيوتر',
        unit: 'جهاز',
        description: 'Core i7 16GB RAM 512GB SSD NVMe',
        quantity: 15,
        purchasePrice: 5000,
        salePrice: 6500,
        wholesalePrice: 5900,
        catalogPrice: 6500,
        catalogDiscountPrice: 6250,
        catalogBadge: '🔥 الأكثر طلباً',
        catalogFeatured: true,
        showInCatalog: true,
        minStockAlert: 3,
        costMethod: 'fifo',
        batches: [
          { id: 'b1', batchNumber: 'LOT-2026-01', expiryDate: '2028-12-31', qty: 15, purchasePrice: 5000 },
        ],
        branchStock: { 'br-main': 10, 'br-branch2': 5 },
        movements: [],
      },
      {
        id: 'i2',
        companyId: 'COMP-000001',
        name: 'طابعة ملونة HP LaserJet Pro',
        barcode: '62210010002',
        category: 'طابعات ومعدات',
        unit: 'طابعة',
        description: 'طابعة ليزر ملونة متعددة المهام واي فاي',
        quantity: 8,
        purchasePrice: 1800,
        salePrice: 2400,
        wholesalePrice: 2150,
        catalogPrice: 2400,
        catalogDiscountPrice: 0,
        catalogBadge: '',
        catalogFeatured: false,
        showInCatalog: true,
        minStockAlert: 2,
        costMethod: 'avg',
        branchStock: { 'br-main': 5, 'br-branch2': 3 },
        movements: [],
      },
      {
        id: 'i3',
        companyId: 'COMP-000001',
        name: 'شاشة 24 بوصة Full HD IPS',
        barcode: '62210010003',
        category: 'شاشات',
        unit: 'شاشة',
        description: 'شاشة 24 بوصة بدون حواف 75Hz HDMI',
        quantity: 12,
        purchasePrice: 1200,
        salePrice: 1650,
        wholesalePrice: 1450,
        catalogPrice: 1650,
        catalogDiscountPrice: 1550,
        catalogBadge: '⭐ عرض خاص',
        catalogFeatured: true,
        showInCatalog: true,
        minStockAlert: 4,
        costMethod: 'avg',
        branchStock: { 'br-main': 8, 'br-branch2': 4 },
        movements: [],
      },
      {
        id: 'i4',
        companyId: 'COMP-000001',
        name: 'ماوس وكيبورد لاسلكي Wireless Combo',
        barcode: '62210010004',
        category: 'إكسسوارات',
        unit: 'طقم',
        description: 'طقم ماوس وكيبورد لاسلكي عربي/إنجليزي',
        quantity: 25,
        purchasePrice: 180,
        salePrice: 290,
        wholesalePrice: 240,
        catalogPrice: 290,
        catalogDiscountPrice: 0,
        catalogBadge: '',
        catalogFeatured: false,
        showInCatalog: true,
        minStockAlert: 5,
        costMethod: 'fifo',
        branchStock: { 'br-main': 15, 'br-branch2': 10 },
        movements: [],
      },
      // منتجات شركة الأمل للتوريدات (معزولة بالكامل)
      {
        id: 'amal-1',
        companyId: 'COMP-000002',
        name: 'ورق تصوير A4 ماليزي دبل إيه Double A (كرتونة 5 رزم)',
        barcode: '62220010001',
        category: 'أوراق ومطبوعات',
        unit: 'كرتونة',
        description: 'ورق تصوير فاخر 80 جرام عالي البياض للتصوير والليزر المكتبي',
        quantity: 45,
        purchasePrice: 650,
        salePrice: 850,
        wholesalePrice: 790,
        catalogPrice: 850,
        catalogDiscountPrice: 810,
        catalogBadge: '🔥 الأكثر مبيعاً',
        catalogFeatured: true,
        showInCatalog: true,
        minStockAlert: 10,
      },
      {
        id: 'amal-2',
        companyId: 'COMP-000002',
        name: 'طابعة فواتير وإيصالات كاشير حرارية Xprinter 80mm USB+LAN',
        barcode: '62220010002',
        category: 'طابعات وكاشير',
        unit: 'طابعة',
        description: 'طابعة إيصالات سريعة مع قاطع آلي تدعم الدرج الإلكتروني وبلوتوث',
        quantity: 18,
        purchasePrice: 1600,
        salePrice: 2200,
        wholesalePrice: 1950,
        catalogPrice: 2200,
        catalogDiscountPrice: 2050,
        catalogBadge: '⭐ ضمان سنتين',
        catalogFeatured: true,
        showInCatalog: true,
        minStockAlert: 3,
      },
      {
        id: 'amal-3',
        companyId: 'COMP-000002',
        name: 'كرتونة بكر كاشير حراري 80*70 مم (50 بكرة)',
        barcode: '62220010003',
        category: 'مستلزمات تشغيل',
        unit: 'كرتونة',
        description: 'ورق حراري نقي خالي من مادة BPA عالي الوضوح لماكينات الكاشير',
        quantity: 35,
        purchasePrice: 420,
        salePrice: 580,
        wholesalePrice: 520,
        catalogPrice: 580,
        catalogDiscountPrice: 0,
        catalogBadge: '',
        catalogFeatured: false,
        showInCatalog: true,
        minStockAlert: 5,
      },
      {
        id: 'amal-4',
        companyId: 'COMP-000002',
        name: 'قارئ باركود لاسلكي 2D مع قاعدة شحن (يدعم QR والباركود العادي)',
        barcode: '62220010004',
        category: 'أجهزة مسح وتتبع',
        unit: 'جهاز',
        description: 'ماسح باركود ذكي يعمل بالبلوتوث والوايرلس 2.4G لمسافة 50 متر',
        quantity: 12,
        purchasePrice: 950,
        salePrice: 1450,
        wholesalePrice: 1250,
        catalogPrice: 1450,
        catalogDiscountPrice: 1350,
        catalogBadge: '💥 خصم 100 ج',
        catalogFeatured: true,
        showInCatalog: true,
        minStockAlert: 2,
      },
    ],
    salesInvoices: [],
    purchaseInvoices: [],
    cashTransactions: [],
    backups: [],
    nextInvoiceNumber: 1,
    nextPurchaseNumber: 1,
    nextCashId: 1,
    cashBox: { drawer: 0, vodafone: 0, instapay: 0, bank: 0 },
    salesReps: [
      { id: 'r1', name: 'أحمد محمود', phone: '01001234567', region: 'القاهرة الكبرى', totalSales: 0, commission: 2.5 },
      { id: 'r2', name: 'محمد علي', phone: '01109876543', region: 'الجيزة والصعيد', totalSales: 0, commission: 2.5 },
    ],
    bankAccounts: [
      { id: 'b1', name: 'البنك الأهلي المصري', accountNumber: '12345678901', balance: 0 },
      { id: 'b2', name: 'بنك مصر', accountNumber: '98765432101', balance: 0 },
      { id: 'b3', name: 'البنك التجاري الدولي CIB', accountNumber: '5544332211', balance: 0 },
    ],
    physicalInventories: [
      {
        id: 'stk-1',
        sessionNumber: 'INV-2026-001',
        title: 'جرد نصف سنوي شامل - المخزن الرئيسي',
        date: '2026-08-15',
        branchId: 'br-main',
        branchName: 'الفرع الرئيسي والمخزن المركزي',
        category: 'الكل',
        status: 'draft',
        items: [
          {
            itemId: 'i1',
            itemName: 'جهاز كمبيوتر Core i7 Desktop',
            barcode: '62210010001',
            category: 'أجهزة كمبيوتر',
            unit: 'جهاز',
            bookQty: 15,
            countedQty: 14,
            varianceQty: -1,
            costPrice: 5000,
            varianceCostTotal: -5000,
            reason: 'shortage_loss',
            notes: 'عجز جهاز واحد قيد الفحص مع موظف الأمن',
          },
          {
            itemId: 'i2',
            itemName: 'طابعة ليزر HP LaserJet Pro',
            barcode: '62210010002',
            category: 'طابعات ومعدات',
            unit: 'طابعة',
            bookQty: 8,
            countedQty: 8,
            varianceQty: 0,
            costPrice: 3200,
            varianceCostTotal: 0,
            reason: 'routine_adjustment',
            notes: 'مطابق تماماً',
          },
          {
            itemId: 'i3',
            itemName: 'شاشة 24 بوصة Full HD IPS',
            barcode: '62210010003',
            category: 'شاشات',
            unit: 'شاشة',
            bookQty: 20,
            countedQty: 20,
            varianceQty: 0,
            costPrice: 1200,
            varianceCostTotal: 0,
            reason: 'routine_adjustment',
            notes: 'مطابق تماماً',
          },
          {
            itemId: 'i4',
            itemName: 'ماوس وكيبورد لاسلكي Wireless Combo',
            barcode: '62210010004',
            category: 'إكسسوارات',
            unit: 'طقم',
            bookQty: 25,
            countedQty: 26,
            varianceQty: 1,
            costPrice: 180,
            varianceCostTotal: 180,
            reason: 'surplus_found',
            notes: 'طقم إضافي من توريدة سابقة',
          },
        ],
        totalItemsCounted: 4,
        matchedItemsCount: 2,
        shortageItemsCount: 1,
        surplusItemsCount: 1,
        totalShortageValue: 5000,
        totalSurplusValue: 180,
        netVarianceValue: -4820,
        committeeMembers: 'أحمد محمود (أمين المخزن)، كريم عادل (عضو الجرد)',
        notes: 'جلسة جرد دورية للمخزن الرئيسي',
        createdBy: 'Mohamed Nazih',
        createdAt: '2026-08-15 09:00',
      },
    ],
    inventoryAdjustments: [],
    goodsIssueVouchers: [
      {
        id: 'gin-88',
        voucherNumber: 'GIN-2026-088',
        date: '2026-08-27',
        time: '11:45 ص',
        sourceBranchId: 'br-main',
        sourceBranchName: 'المخزن الرئيسي',
        recipientName: 'فرع المنتزه / قسم الصيانة',
        recipientType: 'maintenance',
        purposeReason: 'صرف قطع غيار ومستلزمات تشغيل بناءً على طلب الاحتياج رقم (REQ-402) بغرض صيانة وتشغيل خط الإنتاج الثاني.',
        items: [
          {
            itemId: 'i101',
            code: 'ITM-001',
            name: 'كابلات شبكة Cat6 (لفة)',
            unit: 'لفة',
            qty: 5,
            unitCost: 1200.0,
            totalCost: 6000.0,
            notes: 'أصلية معتمدة',
          },
          {
            itemId: 'i102',
            code: 'ITM-045',
            name: 'مفتاح كهرباء ثلاثي معزول',
            unit: 'قطعة',
            qty: 20,
            unitCost: 85.5,
            totalCost: 1710.0,
            notes: 'صناعة إيطالي',
          },
          {
            itemId: 'i103',
            code: 'ITM-102',
            name: 'محول طاقة 12V 5A',
            unit: 'قطعة',
            qty: 8,
            unitCost: 250.0,
            totalCost: 2000.0,
            notes: 'حماية من التردد',
          },
          {
            itemId: 'i104',
            code: 'ITM-308',
            name: 'شريط لاصق عازل (كرتونة)',
            unit: 'كرتونة',
            qty: 2,
            unitCost: 450.0,
            totalCost: 900.0,
            notes: 'مقاوم للحرارة',
          },
        ],
        totalQty: 35,
        totalCost: 10610.0,
        createdBy: 'Mohamed Nazih',
        warehouseKeeper: 'سامح إبراهيم (أمين المخزن)',
        recipientSignatory: 'م. أحمد فؤاد (مشرف الصيانة)',
        approvedBy: 'أ. محمد نزيه (مدير المخازن)',
        status: 'approved',
        notes: 'تم فحص البضاعة ومطابقتها قبل الصرف.',
      },
    ],
    fiscalClosings: [],
    nextStocktakeId: 2,
    nextAdjustmentId: 1,
    nextGoodsIssueId: 89,
    nextClosingId: 1,
    advancedSettings: {
      categories: ['أجهزة كمبيوتر', 'طابعات ومعدات', 'شاشات', 'إكسسوارات', 'شبكات وكاميرات'],
      itemGroups: ['إلكترونيات', 'مكتبية', 'أجهزة ذكية'],
      units: ['جهاز', 'قطعة', 'طقم', 'علبة', 'كرتونة', 'متر'],
    },

    // Enterprise Modules Initial Data:
    accounts: defaultAccountsTree,
    journalEntries: [],
    nextJournalId: 1,
    costCenters: [
      { id: 'cc-1', code: 'CC-01', name: 'المركز العام الرئيسي', manager: 'المدير المالي' },
      { id: 'cc-2', code: 'CC-02', name: 'مشروع مبيعات التوزيع', manager: 'مدير المبيعات' },
      { id: 'cc-3', code: 'CC-03', name: 'فرع الجيزة والمعارض', manager: 'مدير الفرع' },
    ],
    branches: [
      { id: 'br-main', code: 'HQ-01', name: 'الفرع الرئيسي والمخزن المركزي', location: 'القاهرة - المقر الرئيسي', phone: '01029190615', isMain: true, manager: 'Mohamed Nazih' },
      { id: 'br-branch2', code: 'BR-02', name: 'فرع الجيزة والمعرض', location: 'الجيزة - شارع التحرير', phone: '01100000000', isMain: false, manager: 'أحمد محمود' },
    ],
    activeBranchId: 'br-main',
    stockTransfers: [],
    quotations: [],
    nextQuoteId: 1,
    auditLogs: [
      {
        id: 'log-init',
        timestamp: new Date().toISOString().replace('T', ' ').substring(0, 19),
        userName: 'Mohamed Nazih (المدير)',
        action: 'login',
        module: 'النظام العام',
        details: 'تم تشغيل وتهيئة منظومة النزيه ERP الاحترافية بجميع وحدات المحاسبة والربط الضريبي بنجاح.',
      },
    ],
    eInvoiceConfig: {
      taxRegNumber: '123-456-789',
      commercialRegNumber: 'CR-98765',
      branchCode: '0',
      activityCode: '4651',
      posSerial: 'NAZIH-POS-001',
      isEtaConnected: true,
      autoGenerateQr: true,
    },

    // 1. HR & Payroll Initial Data
    employees: [
      {
        id: 'emp-1',
        code: 'EMP-001',
        name: 'كريم عادل الشناوي',
        phone: '01055566778',
        nationalId: '29001011234567',
        department: 'المبيعات والتسويق',
        jobTitle: 'مشرف مبيعات خارجي',
        basicSalary: 7000,
        housingAllowance: 1000,
        transportAllowance: 800,
        otherAllowances: 200,
        insuranceDeduction: 500,
        taxDeduction: 200,
        hireDate: '2024-01-15',
        status: 'active',
        bankAccount: 'EG1200020001000000123456789',
        notes: 'موظف متميز - مسؤول عن منطقة القاهرة والجيزة',
      },
      {
        id: 'emp-2',
        code: 'EMP-002',
        name: 'ياسمين ممدوح فوزي',
        phone: '01122334455',
        nationalId: '29405051234568',
        department: 'الحسابات والمالية',
        jobTitle: 'محاسب عام وتكاليف',
        basicSalary: 8500,
        housingAllowance: 1200,
        transportAllowance: 600,
        otherAllowances: 0,
        insuranceDeduction: 600,
        taxDeduction: 350,
        hireDate: '2023-06-01',
        status: 'active',
        bankAccount: 'EG3400030002000000987654321',
        notes: 'مسؤولة عن تدقيق القيود والإقرارات الضريبية',
      },
      {
        id: 'emp-3',
        code: 'EMP-003',
        name: 'سامح إبراهيم الدسوقي',
        phone: '01299887766',
        department: 'المستودعات واللوجستيات',
        jobTitle: 'أمين مخزن مركزي',
        basicSalary: 6000,
        housingAllowance: 800,
        transportAllowance: 500,
        otherAllowances: 300,
        insuranceDeduction: 450,
        taxDeduction: 150,
        hireDate: '2024-03-10',
        status: 'active',
        notes: 'مسؤول عن أذون الصرف والاستلام',
      },
    ],
    payrollSlips: [],
    nextPayrollId: 1,
    employeeAdvances: [
      {
        id: 'adv-1',
        employeeId: 'emp-1',
        employeeName: 'كريم عادل الشناوي',
        date: '2026-08-01',
        totalAmount: 3000,
        monthlyDeduction: 1000,
        paidAmount: 1000,
        remainingAmount: 2000,
        installmentsCount: 3,
        notes: 'سلفة مصاريف دراسية',
        status: 'active',
      },
    ],

    // 2. Fixed Assets & Depreciation
    fixedAssets: [
      {
        id: 'asset-1',
        code: 'AST-001',
        name: 'سيارة فان لنقل وتوزيع البضائع (تويوتا)',
        category: 'vehicles',
        purchaseDate: '2025-01-01',
        purchasePrice: 450000,
        salvageValue: 50000,
        usefulLifeYears: 5,
        annualDepreciationRate: 20,
        accumulatedDepreciation: 90000,
        netBookValue: 360000,
        location: 'المخزن المركزي - القاهرة',
        status: 'active',
        assetAccountCode: '1201',
        depExpenseAccountCode: '5204',
        notes: 'لوحة أرقام ق ب ر 4589',
      },
      {
        id: 'asset-2',
        code: 'AST-002',
        name: 'سيرفر تخزين بيانات وشبكات Dell PowerEdge',
        category: 'computers',
        purchaseDate: '2025-06-01',
        purchasePrice: 65000,
        salvageValue: 5000,
        usefulLifeYears: 3,
        annualDepreciationRate: 33.33,
        accumulatedDepreciation: 20000,
        netBookValue: 45000,
        location: 'غرفة السيرفرات - المقر الرئيسي',
        status: 'active',
        assetAccountCode: '1202',
        depExpenseAccountCode: '5204',
        notes: 'شامل وحدة UPS ونسخ احتياطي',
      },
    ],
    depreciationLogs: [],

    // 3. Cheques & Notes
    cheques: [
      {
        id: 1,
        chequeNumber: 'CHK-998821',
        bankName: 'البنك الأهلي المصري',
        drawerName: 'شركة النور للتجارة',
        beneficiaryName: 'النزيه للمحاسبة',
        amount: 25000,
        issueDate: '2026-08-15',
        dueDate: '2026-09-01',
        type: 'receivable',
        status: 'under_collection',
        collectingBankAccountId: 'b1',
        notes: 'دفعة تحت حساب فاتورة مبيعات سابقة',
        createdBy: 'Mohamed Nazih',
        createdAt: '2026-08-15 10:30',
      },
      {
        id: 2,
        chequeNumber: 'CHK-441102',
        bankName: 'بنك مصر',
        drawerName: 'النزيه للمحاسبة',
        beneficiaryName: 'مصنع الخير للإلكترونيات',
        amount: 40000,
        issueDate: '2026-08-10',
        dueDate: '2026-09-15',
        type: 'payable',
        status: 'received',
        notes: 'سداد دفعة توريد أجهزة مكتبية',
        createdBy: 'Mohamed Nazih',
        createdAt: '2026-08-10 14:20',
      },
    ],
    nextChequeId: 3,
    commissions: [],

    // 4. Manufacturing & BOM
    boms: [
      {
        id: 'bom-1',
        code: 'BOM-PC-01',
        name: 'تجميع كمبيوتر مكتبي متكامل مع شاشة وملحقات',
        finishedItemId: 'i1',
        finishedItemName: 'جهاز كمبيوتر Core i7 Desktop',
        outputQty: 1,
        rawMaterials: [
          { itemId: 'i3', itemName: 'شاشة 24 بوصة Full HD IPS', unit: 'شاشة', qty: 1, unitCost: 1200, totalCost: 1200 },
          { itemId: 'i4', itemName: 'ماوس وكيبورد لاسلكي Wireless Combo', unit: 'طقم', qty: 1, unitCost: 180, totalCost: 180 },
        ],
        indirectCosts: [
          { name: 'أجور تجميع وفحص فني', cost: 150 },
          { name: 'تغليف وكرتونة خاصة', cost: 70 },
        ],
        totalUnitCost: 1600,
        notes: 'معادلة تجميع معيارية للمنتج الكامل',
        createdAt: '2026-08-01',
      },
    ],
    productionOrders: [],
    nextProductionId: 1,

    // 5. Bank Statements & Reconciliation
    bankStatements: [
      {
        id: 'bs-1',
        bankAccountId: 'b1',
        date: '2026-08-20',
        reference: 'TRF-889922',
        description: 'تحويل وارد من عميل تجاري',
        debit: 0,
        credit: 15000,
        isReconciled: true,
        matchedDate: '2026-08-20',
      },
      {
        id: 'bs-2',
        bankAccountId: 'b1',
        date: '2026-08-22',
        reference: 'CHQ-PAID-01',
        description: 'صرف شيك مورد رقم 441101',
        debit: 12000,
        credit: 0,
        isReconciled: false,
      },
    ],

    // 6. Approval Requests
    approvalRequests: [],

    // 7. Auto Backup & Protection
    autoBackupConfig: {
      enabled: true,
      intervalMinutes: 60, // Every 1 hour
      autoDownloadFile: false,
      maxSnapshotsToKeep: 15,
      lastBackupTimestamp: new Date().toISOString(),
      backupLocation: 'browser_storage',
      notifyOnBackup: true,
    },

    // 8. Multi-Tenant Enterprise Architecture
    companyId: 'COMP-000001',
    companies: DEFAULT_COMPANIES,
    companyCatalogConfigs: {
      'COMP-000001': {
        enabled: true,
        storeName: 'شركة النزيه للمحاسبة والتجارة',
        storeDescription: 'الكتالوج الإلكتروني لأجهزة الكمبيوتر والشاشات والشبكات مع الطلب الفوري',
        contactPhone: '01029190615',
        whatsappNumber: '01029190615',
        allowOnlineOrders: true,
        priceDisplayMode: 'both',
        showStockStatus: true,
        showExactStockQty: false,
        bannerMessage: '🚚 شحن وتوصيل فوري لجميع المحافظات مع ضمان الاستبدال',
        minOrderAmount: 200,
        currencySymbol: 'ج.م',
        autoPrintOrders: true,
        printFormat: '80mm',
        soundAlertEnabled: true,
        companyId: 'COMP-000001',
      },
      'COMP-000002': {
        enabled: true,
        storeName: 'مؤسسة الأمل للتوريدات ومستلزمات الكاشير',
        storeDescription: 'المتجر الإلكتروني لتوريدات الورق الحراري وطابعات الفواتير والأجهزة المكتبية',
        contactPhone: '01011223344',
        whatsappNumber: '01011223344',
        allowOnlineOrders: true,
        priceDisplayMode: 'both',
        showStockStatus: true,
        showExactStockQty: false,
        bannerMessage: '📦 أسعار خاصة وخصومات للكميات والجملة لكراتين بكر الكاشير وورق التصوير',
        minOrderAmount: 150,
        currencySymbol: 'ج.م',
        autoPrintOrders: true,
        printFormat: '80mm',
        soundAlertEnabled: true,
        companyId: 'COMP-000002',
      },
    },
  };
}

export function loadAppData(): AppData {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    const defaults = getDefaultData();
    const storedLogo = localStorage.getItem('company_logo_base64');
    if (raw) {
      const parsed = JSON.parse(raw);
      const mergedSettings = { ...defaults.settings, ...(parsed.settings || {}) };
      if (storedLogo && !mergedSettings.logo && !mergedSettings.logoUrl) {
        mergedSettings.logo = storedLogo;
        mergedSettings.logoUrl = storedLogo;
      }
      // Migrate and ensure all enterprise properties exist seamlessly
      const loaded: AppData = {
        ...defaults,
        ...parsed,
        settings: mergedSettings,
        accounts: parsed.accounts && parsed.accounts.length > 0 ? parsed.accounts : defaults.accounts,
        journalEntries: parsed.journalEntries || defaults.journalEntries,
        costCenters: parsed.costCenters || defaults.costCenters,
        branches: parsed.branches || defaults.branches,
        activeBranchId: parsed.activeBranchId || defaults.activeBranchId,
        stockTransfers: parsed.stockTransfers || defaults.stockTransfers,
        quotations: parsed.quotations || defaults.quotations,
        auditLogs: parsed.auditLogs || defaults.auditLogs,
        eInvoiceConfig: { ...defaults.eInvoiceConfig, ...(parsed.eInvoiceConfig || {}) },
        nextJournalId: parsed.nextJournalId || 1,
        nextQuoteId: parsed.nextQuoteId || 1,

        // Comprehensive modules migration
        employees: parsed.employees && parsed.employees.length > 0 ? parsed.employees : defaults.employees,
        payrollSlips: parsed.payrollSlips || defaults.payrollSlips,
        nextPayrollId: parsed.nextPayrollId || defaults.nextPayrollId,
        employeeAdvances: parsed.employeeAdvances || defaults.employeeAdvances,
        fixedAssets: parsed.fixedAssets && parsed.fixedAssets.length > 0 ? parsed.fixedAssets : defaults.fixedAssets,
        depreciationLogs: parsed.depreciationLogs || defaults.depreciationLogs,
        cheques: parsed.cheques && parsed.cheques.length > 0 ? parsed.cheques : defaults.cheques,
        nextChequeId: parsed.nextChequeId || defaults.nextChequeId,
        commissions: parsed.commissions || defaults.commissions,
        boms: parsed.boms && parsed.boms.length > 0 ? parsed.boms : defaults.boms,
        productionOrders: parsed.productionOrders || defaults.productionOrders,
        nextProductionId: parsed.nextProductionId || defaults.nextProductionId,
        bankStatements: parsed.bankStatements && parsed.bankStatements.length > 0 ? parsed.bankStatements : defaults.bankStatements,
        approvalRequests: parsed.approvalRequests || defaults.approvalRequests,
        physicalInventories: parsed.physicalInventories && parsed.physicalInventories.length > 0 ? parsed.physicalInventories : defaults.physicalInventories,
        inventoryAdjustments: parsed.inventoryAdjustments || defaults.inventoryAdjustments,
        goodsIssueVouchers: parsed.goodsIssueVouchers && parsed.goodsIssueVouchers.length > 0 ? parsed.goodsIssueVouchers : defaults.goodsIssueVouchers || [],
        fiscalClosings: parsed.fiscalClosings || defaults.fiscalClosings || [],
        nextStocktakeId: parsed.nextStocktakeId || defaults.nextStocktakeId || 2,
        nextAdjustmentId: parsed.nextAdjustmentId || defaults.nextAdjustmentId || 1,
        nextGoodsIssueId: parsed.nextGoodsIssueId || defaults.nextGoodsIssueId || 89,
        nextClosingId: parsed.nextClosingId || defaults.nextClosingId || 1,
        autoBackupConfig: { ...defaults.autoBackupConfig, ...(parsed.autoBackupConfig || {}) },
        backups: parsed.backups || defaults.backups || [],
        productPrices: parsed.productPrices || defaults.productPrices || [],
        priceHistories: parsed.priceHistories || defaults.priceHistories || [],

        // Multi-Tenant Isolation
        companies: parsed.companies && parsed.companies.length > 0 ? parsed.companies : defaults.companies,
        companyId: parsed.companyId || defaults.companyId || 'COMP-000001',
        companyCatalogConfigs: {
          ...(defaults.companyCatalogConfigs || {}),
          ...(parsed.companyCatalogConfigs || {}),
        },
      };

      // Ensure all items have a companyId, and seed company 2 items if not present
      if (loaded.items && loaded.items.length > 0) {
        const hasCompany2 = loaded.items.some((it) => it.companyId === 'COMP-000002');
        loaded.items = loaded.items.map((it) => ({
          ...it,
          companyId: it.companyId || 'COMP-000001',
        }));
        if (!hasCompany2) {
          const company2Items = defaults.items.filter((it) => it.companyId === 'COMP-000002');
          loaded.items.push(...company2Items);
        }
      }

      return ensureProductPricesSynced(loaded);
    }
  } catch (e) {
    console.error('Failed to load data:', e);
  }
  return ensureProductPricesSynced(getDefaultData());
}

export function saveAppData(data: AppData): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (e) {
    console.error('Failed to save data:', e);
  }
}

// Helper to append audit logs easily across the app
export function addAuditLog(
  data: AppData,
  action: 'create' | 'update' | 'delete' | 'print' | 'approval' | 'login' | 'transfer',
  module: string,
  details: string
): AppData {
  const currentUserObj = data.users.find((u) => u.id === data.currentUser) || data.users[0];
  const userName = currentUserObj?.name || 'مدير النظام';

  const newLog = {
    id: `log-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
    timestamp: new Date().toISOString().replace('T', ' ').substring(0, 19),
    userName,
    action,
    module,
    details,
  };

  return {
    ...data,
    auditLogs: [newLog, ...(data.auditLogs || [])].slice(0, 500), // keep latest 500
  };
}
